// This file is automatically generated. Do not modify it manually.
// For any changes, please modify the `docs/backend.json` file.

'use client';

import { useState, useEffect } from 'react';
import { doc, onSnapshot, DocumentReference, DocumentData } from 'firebase/firestore';

import { errorEmitter } from '../error-emitter';
import { FirestorePermissionError } from '../errors';

/**
 * A hook that listens for real-time updates to a Firestore document.
 *
 * @param ref The Firestore document reference to listen to.
 * @returns An object containing the document data, loading state, and error state.
 */
export function useDoc<T>(ref: DocumentReference<DocumentData> | null) {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    if (!ref) {
      setLoading(false);
      return;
    }

    const unsubscribe = onSnapshot(
      ref,
      (snapshot) => {
        if (snapshot.exists()) {
          const data = { id: snapshot.id, ...snapshot.data() } as unknown as T;
          setData(data);
        } else {
          setData(null);
        }
        setLoading(false);
      },
      (err) => {
        setError(err);
        setLoading(false);

        // Throw a custom error to be caught by the FirebaseErrorListener
        // and displayed in the Next.js error overlay.
        const permissionError = new FirestorePermissionError({
          path: ref.path,
          operation: 'get',
        });
        errorEmitter.emit('permission-error', permissionError);
      }
    );

    return () => unsubscribe();
  }, [JSON.stringify(ref)]);

  return { data, loading, error };
}
