// This file is automatically generated. Do not modify it manually.
// For any changes, please modify the `docs/backend.json` file.

'use client';

import { useState, useEffect } from 'react';
import {
  collection,
  onSnapshot,
  Query,
  DocumentData,
} from 'firebase/firestore';

import { errorEmitter } from '../error-emitter';
import { FirestorePermissionError } from '../errors';

/**
 * A hook that listens for real-time updates to a Firestore collection.
 * It can be used with a query to filter and sort the data.
 *
 * @param query The Firestore query to listen to.
 * @returns An object containing the collection data, loading state, and error state.
 */
export function useCollection<T>(query: Query<DocumentData> | null) {
  const [data, setData] = useState<T[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    if (!query) {
      setLoading(false);
      return;
    }

    const unsubscribe = onSnapshot(
      query,
      (snapshot) => {
        const data: T[] = snapshot.docs.map((doc) => ({
          id: doc.id,
          ...doc.data(),
        } as unknown as T));
        setData(data);
        setLoading(false);
      },
      (err) => {
        setError(err);
        setLoading(false);

        // Throw a custom error to be caught by the FirebaseErrorListener
        // and displayed in the Next.js error overlay.
        const permissionError = new FirestorePermissionError({
          path: query.path,
          operation: 'list',
        });
        errorEmitter.emit('permission-error', permissionError);
      }
    );

    return () => unsubscribe();
  }, [JSON.stringify(query)]);

  return { data, loading, error };
}
