// This file is automatically generated. Do not modify it manually.
// For any changes, please modify the `docs/backend.json` file.

'use client';
import { ReactNode, useMemo } from 'react';
import { initializeFirebase, FirebaseProvider, FirebaseErrorListener } from '@/firebase';

export default function FirebaseClientProvider({
  children
}: {
  children: ReactNode
}) {
  const firebaseApp = useMemo(() => initializeFirebase(), []);

  return (
    <FirebaseProvider {...firebaseApp}>
      <FirebaseErrorListener/>
      {children}
    </FirebaseProvider>
  );
}
