// This file is automatically generated. Do not modify it manually.
// For any changes, please modify the `docs/backend.json` file.

// The following configuration is for a Firebase project.
// This is a public configuration and can be securely shared.
// For more information, see: https://firebase.google.com/docs/projects/learn-more#config-files-objects

export const firebaseConfig = {"projectId":"next-js-starter-1e967","appId":"1:325968383393:web:5317377508932688439a3f","storageBucket":"next-js-starter-1e967.appspot.com","apiKey":"mock-key","authDomain":"next-js-starter-1e967.firebaseapp.com","messagingSenderId":"325968383393"};
export const firebaseProjectId = "next-js-starter-1e967";
