// This file is automatically generated. Do not modify it manually.
// For any changes, please modify the `docs/backend.json` file.

'use client';

import React from 'react';
import { errorEmitter } from './error-emitter';

/**
 * The context for a security rule error.
 */
export type SecurityRuleContext = {
  path: string;
  operation: 'get' | 'list' | 'create' | 'update' | 'delete';
  requestResourceData?: any;
};

/**
 * A custom error for Firestore permission errors that includes the
 * context of the security rule that failed.
 */
export class FirestorePermissionError extends Error {
  public readonly name = 'FirestorePermissionError';
  public readonly context: SecurityRuleContext;

  constructor(context: SecurityRuleContext) {
    super(
      `FirestoreError: Missing or insufficient permissions: The following request was denied by Firestore Security Rules:\n${JSON.stringify(context, null, 2)}`,
    );
    this.context = context;
  }
}

/**
 * A React component that listens for 'permission-error' events and
 * throws them as uncaught exceptions so they can be picked up by
 * the Next.js error overlay.
 *
 * This component should be placed at the root of the application.
 */
export function FirebaseErrorListener() {
  React.useEffect(() => {
    const throwError = (error: Error) => {
      // Throw the error in a timeout to avoid React catching it
      // in its own error boundary.
      setTimeout(() => {
        throw error;
      });
    };

    errorEmitter.on('permission-error', throwError);
    return () => {
      errorEmitter.off('permission-error', throwError);
    };
  }, []);

  return null;
}
