// This file is automatically generated. Do not modify it manually.
// For any changes, please modify the `docs/backend.json` file.

type EventMap = {
  'permission-error': (error: Error) => void;
};

class ErrorEventEmitter {
  private listeners: { [K in keyof EventMap]?: EventMap[K][] } = {};

  on<K extends keyof EventMap>(event: K, listener: EventMap[K]) {
    if (!this.listeners[event]) {
      this.listeners[event] = [];
    }
    this.listeners[event]?.push(listener);
  }

  off<K extends keyof EventMap>(event: K, listener: EventMap[K]) {
    if (!this.listeners[event]) {
      return;
    }
    this.listeners[event] = this.listeners[event]?.filter(l => l !== listener);
  }

  emit<K extends keyof EventMap>(event: K, ...args: Parameters<EventMap[K]>) {
    if (!this.listeners[event]) {
      return;
    }
    this.listeners[event]?.forEach(listener => {
      listener(...(args as any[]));
    });
  }
}

export const errorEmitter = new ErrorEventEmitter();
