// This file is automatically generated. Do not modify it manually.
// For any changes, please modify the `docs/backend.json` file.

import { initializeApp, getApps, type FirebaseApp } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore } from 'firebase/firestore';

import { firebaseConfig } from './config';
import { FirebaseErrorListener } from './errors';
import { FirebaseProvider, useFirebase, useFirebaseApp, useFirestore, useAuth } from './provider';
import { useCollection } from './firestore/use-collection';

/**
 * Initializes the Firebase app, returning the app, auth, and firestore instances.
 * It is idempotent, meaning it will only initialize the app once.
 *
 * @returns {{app: FirebaseApp, auth: Auth, firestore: Firestore}}
 * The initialized Firebase app, auth, and firestore instances.
 */
function initializeFirebase() {
  const apps = getApps();
  const app = apps.length ? apps[0] : initializeApp(firebaseConfig);
  const auth = getAuth(app);
  const firestore = getFirestore(app);
  return { app, auth, firestore };
}

export {
  initializeFirebase,
  FirebaseProvider,
  FirebaseErrorListener,
  useCollection,
  useFirebase,
  useFirebaseApp,
  useFirestore,
  useAuth,
};

export type { FirebaseApp };
