// This file is automatically generated. Do not modify it manually.
// For any changes, please modify the `docs/backend.json` file.

'use client';

import {
  createContext,
  useContext,
  type ReactNode,
} from 'react';

import type { Auth } from 'firebase/auth';
import type { FirebaseApp } from 'firebase/app';
import type { Firestore } from 'firebase/firestore';

export interface FirebaseContextValue {
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
}

const FirebaseContext = createContext<FirebaseContextValue | undefined>(undefined);

export interface FirebaseProviderProps extends FirebaseContextValue {
  children: ReactNode;
}

export function FirebaseProvider({
  children,
  ...value
}: FirebaseProviderProps) {
  return (
    <FirebaseContext.Provider value={value}>
      {children}
    </FirebaseContext.Provider>
  );
}

export function useFirebase() {
  const context = useContext(FirebaseContext);
  if (context === undefined) {
    throw new Error('useFirebase must be used within a FirebaseProvider');
  }
  return context;
}

export function useFirebaseApp() {
  const { app } = useFirebase();
  return app;
}

export function useFirestore() {
  const { firestore } = useFirebase();
  return firestore;
}

export function useAuth() {
  const { auth } = useFirebase();
  return auth;
}
